language: php

php:
  - 5.4

before_script:
  - npm install --silent -g zombie > /dev/null
  - export NODE_PATH=/home/vagrant/.nvm/v0.4.12/lib/node_modules:/usr/local/lib/node_modules
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install

script: phpunit -c app
