language: php

php:
  - 5.4

before_script:
  - npm install -g zombie
  - export NODE_PATH=/home/vagrant/.nvm/v0.4.12/lib/node_modules:/usr/local/lib/node_modules
  - ls /home/vagrant/.nvm/
  - ls /usr/local/lib/node_modules/
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install

script: phpunit -c app
